function [ spikes ] = nb_import_chronux( filename )
%   Neurobehavior by Buran BN and Sanes DH
%   
%   NB_IMPORT_CHRONUX Load spike waveforms from HDF5 file into Matlab
%
%   filename : string
%       name of file to load data from (must be generated by the
%       review_physiology.py script in the neurobehavior module).
%
%   Returns struct containing spike waveform data that can be used directly by
%   Chronux.

    spikes = nb_import_spikes(filename);
    spikes.Fs = double(h5readatt(filename, '/event_data/waveforms', 'fs'));

    % Collapse the waveform across channels so a single event is viewed as the
    % composite waveform across all channels.
    spikes.waveforms = spikes.waveforms(:,:);
    % transpose b/c of error in ss_aggregate when array is the other way
    spikes.spiketimes = spikes.indices'./spikes.Fs; 

    % Add 1 to align sample to compensate for the difference between Python's
    % 0-based index and Matlab's 1-based index scheme.
    align_sample = double(h5readatt(filename, '/event_data', 'samples_before'));
    spikes.threshT = align_sample + 1;
    spikes.thresh = double(h5readatt(filename, '/event_data', 'threshold'));
end
